/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package linketinder

import linketinder.view.Menu
import linketinder.db.ConfigDatabase

class App {
    static void main(String[] args) {
        ConfigDatabase configDatabase = ConfigDatabase.getInstance();
        Menu menu = new Menu(configDatabase)
        Reader reader = new BufferedReader(new InputStreamReader(System.in))
        menu.exibirMenu(reader)
    }
}
